secrets:
  mysql_root_password:
    file: "${MYSQL_ROOT_PASSWORD_SECRET_PATH:?MYSQL_ROOT_PASSWORD_SECRET_PATH is required}"
  mysql_app_password:
    file: "${MYSQL_APP_PASSWORD_SECRET_PATH:?MYSQL_APP_PASSWORD_SECRET_PATH is required}"
  mysql_url:
    file: "${MYSQL_URL_SECRET_PATH:?MYSQL_URL_SECRET_PATH is required}"
  jwt_secret_key:
    file: "${JWT_SECRET_KEY_SECRET_PATH:?JWT_SECRET_KEY_SECRET_PATH is required}"
  default_admin_password:
    file: "${DEFAULT_ADMIN_PASSWORD_SECRET_PATH:?DEFAULT_ADMIN_PASSWORD_SECRET_PATH is required}"

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: !reset null
      MYSQL_PASSWORD: !reset null
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_app_password
    secrets:
      - source: mysql_root_password
        target: mysql_root_password
      - source: mysql_app_password
        target: mysql_app_password

  train-factory-api:
    environment:
      MYSQL_URL: !reset null
      MYSQL_APP_PASSWORD: !reset null
      JWT_SECRET_KEY: !reset null
      DEFAULT_ADMIN_PASSWORD: !reset null
      MYSQL_URL_FILE: /run/secrets/mysql_url
      JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
      DEFAULT_ADMIN_PASSWORD_FILE: /run/secrets/default_admin_password
    secrets:
      - source: mysql_url
        target: mysql_url
      - source: jwt_secret_key
        target: jwt_secret_key
      - source: default_admin_password
        target: default_admin_password

  train-factory-api-dev:
    environment:
      MYSQL_URL: !reset null
      MYSQL_APP_PASSWORD: !reset null
      JWT_SECRET_KEY: !reset null
      DEFAULT_ADMIN_PASSWORD: !reset null
      MYSQL_URL_FILE: /run/secrets/mysql_url
      JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
      DEFAULT_ADMIN_PASSWORD_FILE: /run/secrets/default_admin_password
    secrets:
      - source: mysql_url
        target: mysql_url
      - source: jwt_secret_key
        target: jwt_secret_key
      - source: default_admin_password
        target: default_admin_password
