"""
Prompt 模板

提供数据生成各步骤的 Prompt 模板。
"""

from .default_prompts import (
    # 类型定义
    SOURCE_TYPES,
    LENGTH_TYPES,
    LENGTH_TYPE_NAMES,
    SOURCE_LENGTH_DISTRIBUTION,
    # 辅助函数
    get_source_info,
    sample_source_config,
    # 角色生成
    ROLE_GENERATION_PROMPT,
    ROLE_GENERATION_FROM_DOC_PROMPT,
    # QA 生成
    QA_GENERATION_PROMPT,
    QA_GENERATION_WITH_ROLE_PROMPT,
    KEYPOINT_EXTRACTION_PROMPT,
    # 正负例生成
    POSITIVE_CHUNK_PROMPT,
    NEGATIVE_CHUNK_PROMPT,
    POSITIVE_CHUNK_WITH_ROLE_PROMPT,
    NEGATIVE_CHUNK_WITH_ROLE_PROMPT,
    # 校验
    VALIDATION_PROMPT,
    # 文档质量
    DOC_QUALITY_PROMPT,
)

from .statement_prompts import (
    # 语句提取（statement 模式）
    NEG_EXTRACTION_SYSTEM_PROMPT,
    NEG_EXTRACTION_USER_TEMPLATE,
    POS_EXTRACTION_SYSTEM_PROMPT,
    POS_EXTRACTION_USER_TEMPLATE,
    POS_CONFIRM_SYSTEM_PROMPT,
    POS_CONFIRM_USER_TEMPLATE,
    NEG_CONFIRM_SYSTEM_PROMPT,
    NEG_CONFIRM_USER_TEMPLATE,
    # Answer 重述 / 证据操作
    ANSWER_REWRITE_SYSTEM_PROMPT,
    ANSWER_REWRITE_USER_TEMPLATE,
    EVIDENCE_REMOVAL_SYSTEM_PROMPT,
    EVIDENCE_REMOVAL_USER_TEMPLATE,
    EVIDENCE_PRUNING_SYSTEM_PROMPT,
    EVIDENCE_PRUNING_USER_TEMPLATE,
)

from .prompt_manager import PromptManager

__all__ = [
    # 类型定义
    "SOURCE_TYPES",
    "LENGTH_TYPES",
    "LENGTH_TYPE_NAMES",
    "SOURCE_LENGTH_DISTRIBUTION",
    # 辅助函数
    "get_source_info",
    "sample_source_config",
    # 角色生成
    "ROLE_GENERATION_PROMPT",
    "ROLE_GENERATION_FROM_DOC_PROMPT",
    # QA 生成
    "QA_GENERATION_PROMPT",
    "QA_GENERATION_WITH_ROLE_PROMPT",
    "KEYPOINT_EXTRACTION_PROMPT",
    # 正负例生成
    "POSITIVE_CHUNK_PROMPT",
    "NEGATIVE_CHUNK_PROMPT",
    "POSITIVE_CHUNK_WITH_ROLE_PROMPT",
    "NEGATIVE_CHUNK_WITH_ROLE_PROMPT",
    # 校验
    "VALIDATION_PROMPT",
    # 文档质量
    "DOC_QUALITY_PROMPT",
    # 语句提取（statement 模式）
    "NEG_EXTRACTION_SYSTEM_PROMPT",
    "NEG_EXTRACTION_USER_TEMPLATE",
    "POS_EXTRACTION_SYSTEM_PROMPT",
    "POS_EXTRACTION_USER_TEMPLATE",
    "POS_CONFIRM_SYSTEM_PROMPT",
    "POS_CONFIRM_USER_TEMPLATE",
    "NEG_CONFIRM_SYSTEM_PROMPT",
    "NEG_CONFIRM_USER_TEMPLATE",
    # Answer 重述 / 证据操作
    "ANSWER_REWRITE_SYSTEM_PROMPT",
    "ANSWER_REWRITE_USER_TEMPLATE",
    "EVIDENCE_REMOVAL_SYSTEM_PROMPT",
    "EVIDENCE_REMOVAL_USER_TEMPLATE",
    "EVIDENCE_PRUNING_SYSTEM_PROMPT",
    "EVIDENCE_PRUNING_USER_TEMPLATE",
    # 管理器
    "PromptManager",
]
